### ISSUE TITLE
when adding a new domain <domain>.cfg.lua reference private key owned by root

### ISSUE THREAD

**Issue by artlog** [YunoHost/metronome#13]
I aml trying to activate a jitsi conference on one serveur with yunohost
i had to create many subdomains.
i have error in /var/log/metronome/metronome.err claiming 
Mar 20 06:25:02 certmanager	error	SSL/TLS: Failed to load '/etc/yunohost/certs/serveur.slv-valbonne.fr/key.pem': Check that the permissions allow Metronome to read this file. (for serveur.slv-valbonne.fr)
 ( and others )

metronome is launched with user metronome so it looks normal to not be able to read private key.
Do i have something wrong in my configuration or is it a general matter ?

I am not sure yet ssl is required to have jitsi working with xmpp but it currently does not work at all so i am investigating any mis-configuration.

**Comment by alexAubin** [comment]
Not sure exactly as it somewhat depends if you have Lets Encrypt or not. Anyway, certs should be readable by group ssl-cert, which metronome should be a member of. Dunno if that solves the issue or not, but I can't really help more without details as in, for example, are you using the jitsi_ynh app or a custom install ...

Anyway, I'm closing the issue here as it's not the right place to post issue. Instead, you should post here https://github.com/yunohost/issues/issues (or on the forum)
